### ISSUE TITLE
DB Exception on load when Sonarr installed

### ISSUE THREAD

**Issue by fedoranimus** [galli-leo/Radarr#10]
The system will run fine until I try to load the UI through the browser, then the following exception will be thrown. This may be because I have set up Sonarr on this system in the past and the DB cannot update properly.

```
System.Data.SQLite.SQLiteException occurred
  HResult=0x80004005
  Message=SQL logic error or missing database
no such table: Movies
```

**Comment by galli-leo** [comment]
Hmm, it should have generated the Movies table automatically. Do you have the regular Sonarr installed as well?

**Comment by fedoranimus** [comment]
With the change you suggested, it now cannot find column `t0.ProfileId` on the `GetAllMovies()` request.

**Comment by galli-leo** [comment]
I know what's causing that. But because I am currently away from my computer I can only fix that tomorrow. Unless you know how to edit a sqlite database directly.

**Comment by fedoranimus** [comment]
I do, but I'm headed out for the evening as well. We can dig into this tomorrow.
