### ISSUE TITLE
Backup/update fail Access to the path "/tmp/nzbdrone_backup/config.xml" is denied

### ISSUE THREAD

**Issue by schumi2004** [galli-leo/Radarr#104]
Something has changed in update/backup mechanism.
I found a issue were this commit was mentioned and should fix it https://github.com/galli-leo/Radarr/commit/d62dbd48ae60a7d878f24fba04e1d4ff561edbd2#diff-82dda069ae275373e5dbc01c1d976f43 but it's still here in my Synology package (v0.2.0.32).
This package is essentially the same as the normal Sonarr package provided by SynoCommunity

Manual backup:
Error occurred while executing task Backup: Access to the path "/tmp/nzbdrone_backup/config.xml" is denied.

Manual update:
Error occurred while executing task ApplicationUpdate: Access to the path "/tmp/nzbdrone_backup/config.xml" is denied.

Only difference i see with Sonarr and Radarr is this line in previous mentioned commit:
https://github.com/galli-leo/Radarr/commit/d62dbd48ae60a7d878f24fba04e1d4ff561edbd2#diff-82dda069ae275373e5dbc01c1d976f43R20

I could give access to this folder for Radarr but that defeats the purpose of a package ;)

**Comment by onedr0p** [comment]
I can confirm that the path `/tmp/nzbdrone_backup/` is the same still here in Radarr.

`/tmp/radarr_update/` is however working fine.

**Comment by schumi2004** [comment]
Strange though since i can't find path in current code, did something go wrong during compile maybe?

**Comment by onedr0p** [comment]
I believe that commit should solve our problems.

**Comment by onedr0p** [comment]
We will try this with the new release and make sure it indeeds uses the correct path.
