### ISSUE TITLE
Missing movie posters in search results

### ISSUE THREAD

**Issue by schumi2004** [galli-leo/Radarr#106]
When searching for a movie (yeah, works perfect now!) the poster images are missing.
This is in version 0.2.0.45 but was also present in version 0.2.0.32
![imgur](https://cloud.githubusercontent.com/assets/968545/21819152/dafed468-d76a-11e6-8e9e-9afce26cd183.PNG)

**Comment by galli-leo** [comment]
Hmm, works fine for me. Can you open the developer console of chrome, redo the search and check if any errors are present?

**Comment by onedr0p** [comment]
Turn off adblock and Privacy Badger

**Comment by schumi2004** [comment]
Your right @onedr0p my bad, sorry.

ERR_BLOCKED_BY_CLIENT
