### ISSUE TITLE
Decouple the application from NzbDrone

### ISSUE THREAD

**Issue by galli-leo** [galli-leo/Radarr#11]
This is needed to run Sonarr and Radarr side by side:

- [x] Change data storage location (Fixed, see: #10 )
- [x] Change exe names.
- [x] Do not check for NzbDrone running, but Radarr. (Hacky fix)
- [x] Use different standard port than Sonarr.

**Comment by scalda** [comment]
I was just about to post about the fact you can't run sonarr and radarr together then found this, so until this is fixed I can't test and use sadly. but I am hoping you can get it done soon as this is something that is really needed

**Comment by scalda** [comment]
Nice one thanks I'll test it once I'm home

**Comment by tymanthius** [comment]
I just grabbed that and tested it. It's better, but appears to still be trying to use port 8989.

Here's the tail end of everything that scrolls by:

[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:8989/
[Info] NancyBootstrapper: Starting NzbDrone API
[Info] ProfileService: Setting up default quality profiles


[Fatal] ConsoleApp: Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions

**Comment by wkupike2000** [comment]
Am I understanding you that even though the .exe is the same name this can be ran simultaneously with Sonarr? I can't quite understand how if so. Thanks!

**Comment by tymanthius** [comment]
I can verify that under linux, using mono, it works.

**Comment by galli-leo** [comment]
@wkupike2000 Yep that's correct.

**Comment by wkupike2000** [comment]
I should clarify, I'm on Windows version

**Comment by fedoranimus** [comment]
@wkupike2000 .exe names are for the user's sake - the OS doesn't really care. It's reading the code in the .exe.

We can update the name of the .exe soon.
