### ISSUE TITLE
Cannot launch Mac Version

### ISSUE THREAD

**Issue by galli-leo** [galli-leo/Radarr#15]
This is a problem because of ms dos line endings.

**Comment by brianmbutler** [comment]
New error.. "“%@” can’t be found."

**Comment by galli-leo** [comment]
@brianmbutler Seems to be working for me. Try redownloading it.

**Comment by brianmbutler** [comment]
Sorry, still having the same error, I just downloaded it again.

**Comment by galli-leo** [comment]
Can you post the whole log? Then it's easier to pinpoint the issue.

**Comment by brianmbutler** [comment]
I have no idea what happened, but it’s working now.   I did update Mono, who knows.   Working fine though, thanks.

Any way on the next batch to change the build script to name the file Radarr.app instead of Sonarr.app?

**Comment by galli-leo** [comment]
Great that it works. Yea I am going to change that soon.

**Comment by brianmbutler** [comment]
on release e I'm getting a "The application Radarr can't be opened" error popup.

**Comment by galli-leo** [comment]
I have added a fixed version of the osx package to the release page.

**Comment by galli-leo** [comment]
@brianmbutler Does it work now?

**Comment by brianmbutler** [comment]
Yes.  No issue.  Can close.

**Comment by golimpio** [comment]
This is still happening, the Radarr application is not set as an executable (missing the executable attribute).

Workaround:
`chmod +x /Applications/Media Center/Radarr.app/Contents/MacOS/Radarr`

See also:
- https://www.reddit.com/r/radarr/comments/5tzvz4/osx_the_application_radarr_cant_be_opened/
