### ISSUE TITLE
Does not run on same machine as sonarr

### ISSUE THREAD

**Issue by tymanthius** [galli-leo/Radarr#16]
Just grapped the latest exe and installed on a debian system with mono that's been happily running sonarr for several months.

This is the msg I get: 

root@dvr:/opt/Radarr# mono NzbDrone.exe
[Info] Bootstrap: Starting Sonarr - /opt/Radarr_Mono_v0.1-b/NzbDrone.exe - Version 10.0.0.24115
[Info] SingleInstancePolicy: 1 instance(s) of Sonarr are running
[Warn] SingleInstancePolicy: Another instance of Sonarr is already running.
[Info] Bootstrap: Application is being terminated. Reason : Another instance is already running
 

Yes, I started it as root, but that was to be sure it didn't overwrite my users nzbdrone config files.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by galli-leo** [comment]
Have you tried going to http://localhost:7878 on your machine?

That should have been fixed in v0.1-b. However, it still gives the error message, it just then ignores it.

**Comment by tymanthius** [comment]
I will test & report back.  Working remotely at the moment.

**Comment by tymanthius** [comment]
Just duplicating this comment here to keep the thread stable:

I just grabbed that and tested it. It's better, but appears to still be trying to use port 8989.

Here's the tail end of everything that scrolls by:

[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController: http://*:8989/
[Info] NancyBootstrapper: Starting NzbDrone API
[Info] ProfileService: Setting up default quality profiles

[Fatal] ConsoleApp: Address already in use. This can happen if another instance of Sonarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions

**Comment by galli-leo** [comment]
Have you tried redownloading it? I think I screwed up when zipping up the release and it was actually an old version.

**Comment by tymanthius** [comment]
I re-downloaded after you posted this and same issue.

**Comment by galli-leo** [comment]
@tymanthius Nevermind, I think I figured out the issue. Can you try to delete this folder: https://github.com/Sonarr/Sonarr/wiki/AppData-Directory (Just instead of NzbDrone it's Radarr).

**Comment by tymanthius** [comment]
That's what it was - after the 'bad start' it had left the old, incorrect, config files.  

It's up and running.  Now I'll play with it. You can close this bug.  :)

**Comment by galli-leo** [comment]
Great to hear it works now.
