### ISSUE TITLE
Fix Media Management Tab

### ISSUE THREAD

**Issue by fedoranimus** [galli-leo/Radarr#18]
**Episode Naming**
Standard Movie Format:
{Movie Title} ({Release Year}) {Quality Full}

Standard Movie Format:
Movie Title (2010) HDTV-720p Proper

Folder Example:
Movie Title (2010)

Options to remove
- [x] Series
- [x] Season
- [x] Episode
- [x] Episode Title

Options to add
- [x] Movie

**Folders**
"Create empty series folders" -> "Create empty movie folders"

**Importing**
N/A

**File Management**
"Ignore Deleted Episodes" -> "Ignore Deleted Movies"

**Permissions**
N/A

**Comment by galli-leo** [comment]
We also should implement this change in C#. Currently movies are not renamed, regardless of the settings.

**Comment by fedoranimus** [comment]
Yes, we'll have to do quite a bit of this on the C# side, especially with the renaming options.

**Comment by fedoranimus** [comment]
Closed by #38 .
