### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by githubmonkey1** [galli-leo/Radarr#21]
Everytime i start the NzbDrone.exe I get this error:

---------------------------
Epic Fail!
---------------------------
TypeInitializationException: Der Typeninitialisierer für "System.Data.SQLite.SQLiteFactory" hat eine Ausnahme verursacht.
---------------------------
OK   
---------------------------

The browser opens the localhost page, but is unable to connect to anything. The process is also not in the task manager. 

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by galli-leo** [comment]
Have you tried redownloading it? (Should have fixed in the zip file name).

The error should be fixed in the latest download.

**Comment by githubmonkey1** [comment]
That was the problem. Thanks for your fast response and keep up the good work! :) 👍
