### ISSUE TITLE
Failed to get/refresh movie info

### ISSUE THREAD

**Issue by tymanthius** [galli-leo/Radarr#26]
When I add a new movie or refresh a movie on .1-d it fails.

Log shows: Error while executing RefreshMovie: Newtonsoft.json.linq.jobject does not contain a definition for title.

Provide a description of the feature request or bug, the more details the better.
Please use https://forums.sonarr.tv/ for support or other questions. (When in doubt, use the forums)

**Comment by galli-leo** [comment]
We now use The Movie DB for getting metadata. Can you try downloading the latest release and trying again?

**Comment by tymanthius** [comment]
That fixed this issue.  :)  Now to get a movie to download. :D
