### ISSUE TITLE
Running Sonarr & Radarr at the same time

### ISSUE THREAD

**Issue by bakthomas** [galli-leo/Radarr#29]
I am having an issue running Sonarr and Radarr at the same time.
If I run Sonarr first, and I run Radarr.
However, if Radarr first, Sonarr will not run. 

I get the following in the console When running Sonarr while Radarr is already running.

[Info] Bootstrap: Starting Sonarr - C:\programData\NzbDrone\bin\NzbDrone.Console.exe - Version 2.0.0.45.3
[Info] SingleInstancePolicy: 1 instance(s) of Sonarr are running
[Warn] SingleInstancePolicy: Another instance of Sonarr is already running
[Info] BrowserServcie: Starting default browser. http://localhost:8989
[Info] processService: Opening URL [http://localhost;8989]
[Info] Bootstrap: Application is being terminated. Reason : Another instance is already running

But if I start Sonarr first, then start Radarr they both work with this in the console

[Info] Bootstrap: Starting Sonarr - C:\Users\Plex\Desktop\Radarr_Windows_v0.1-e\
NzbDrone.Console.exe - Version 10.0.0.26858
[Info] SingleInstancePolicy: 1 instance(s) of Sonarr are running
[Warn] SingleInstancePolicy: Another instance of Sonarr or Radarr is already run
ning.
[Info] BrowserService: Starting default browser. http://localhost:7878
[Info] ProcessProvider: Opening URL [http://localhost:7878]
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\nzbdrone
.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=
3 ***
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\logs.db;
cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 **
*
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:7878/
[Info] NancyBootstrapper: Starting NzbDrone API
[Info] BrowserService: Starting default browser. http://localhost:7878
[Info] ProcessProvider: Opening URL [http://localhost:7878]

Easy answer is to run Sonarr first, then Radarr, but fo some reason, since installing Radarr, Sonarr randomly shuts down.

Clearly you guys are still working on this. But can I just say what an amazing effort you guys have made in the short time since you started this project.

**Comment by galli-leo** [comment]
Thanks for the kind words! The issue should hopefully be fixed in the next release.

**Comment by galli-leo** [comment]
Fixed in latest release
