### ISSUE TITLE
Web gui only opens on localhost:8988

### ISSUE THREAD

**Issue by scalda** [galli-leo/Radarr#41]
Web gui only opens on localhost:8988 where the install of radarr is, so I can't access the web gui from another machine on the same network or externally. the only thing I have changed to do with access is enable user/pass and changed the default port.

Any ideas would be great 

thanks

**Comment by galli-leo** [comment]
Are you running it on windows? Because under windows you need to launch it as admin to connect to it from other machines.

**Comment by scalda** [comment]
Yes i am running windows, and that would explain why then thanks

**Comment by galli-leo** [comment]
@scalda Does it work now?

**Comment by scalda** [comment]
Yes it does via running as a admin. Will this change in the future?

**Comment by galli-leo** [comment]
No. Sadly this is a limitation of Windows. However, it makes sense, as you do not want any application to just send data to the web directly.

**Comment by scalda** [comment]
Oh that's strange as I don't need to with sonarr

**Comment by galli-leo** [comment]
Maybe, it's because their application is signed or something like that. If that's the case, we will change that in the future.

**Comment by scalda** [comment]
I now have the program and all it's files in a bin folder in the radarr folder in C:/programdata the same as how sonarr has theirs and I no longer need to run the exe with admin rights to get access via another pc on my network

**Comment by CBers** [comment]
Same here as @scalda.

Set up in ProgramData and no need to "Run as Administrator".

**Comment by galli-leo** [comment]
Great to hear that.
