### ISSUE TITLE
Unable to connect to nzb.cat

### ISSUE THREAD

**Issue by nitetweaker** [galli-leo/Radarr#49]
I can connect to nzb.cat in Sonarr fine. Copied the same config settings to Radarr, keep getting the following message:

No results were returned from your indexer, please check your settings.

**Comment by AeonLucid** [comment]
I fixed this in https://github.com/galli-leo/Radarr/commit/c63704ba0d57c88e09c80b9527fa8a9fd95d5902, please wait until a new release or download the latest from readme.
