### ISSUE TITLE
Cannot import movies on local disk

### ISSUE THREAD

**Issue by AuXBoX** [galli-leo/Radarr#52]
I have updated to Radarr.develop.0.2.0.2.linux and when i try to import from local disk i get this error
**[Warn] NzbDroneErrorPipeline: Invalid request Validation failed: 
 -- Path is already configured as a root folder**
I previously added all the locations of my movies. Now the locations do not appear and when i try to add them i get this error.

**Comment by fedoranimus** [comment]
Did you remove the path to your movies before trying to add it again?

**Comment by AuXBoX** [comment]
It is not listed anymore

**Comment by AuXBoX** [comment]
It's good now. The folders have popped up. Not sure why it took so long.
Thanks

**Comment by fedoranimus** [comment]
If there are a lot of movies in the path it can take a while to populate.

Glad it's working; I'll keep this issue in mind.
