### ISSUE TITLE
Import existing movies on disk issue

### ISSUE THREAD

**Issue by jOOc** [galli-leo/Radarr#56]
Maybe this is by design but when Import existing movies on disk its only finding movies that have their own sub directory, not files directly under the chosen directory.

**Comment by fedoranimus** [comment]
This is by design.

Radarr looks for directories and parses the name of those to determine what movie will be inside it, similar to how a series works in Sonarr.

Plex also prefers movies to be inside directories; it helps with things such as subtitle organization.

**Comment by jOOc** [comment]
Thank you. Ill move my movies into subdirs.
