### ISSUE TITLE
Unable to add a download client on macOS

### ISSUE THREAD

**Issue by petercockroach** [galli-leo/Radarr#62]
Radarr Ver. 0.2.0.2
After install, I attempted to add a download client for NZBGet. When selecting "Test" or "Save", the dialog box disappears and the client is not added. This also occurs for Sabnzb so I assume it's all download clients. I am able to add indexers successfully which (I believe) rules out a permissions issue.

**Comment by galli-leo** [comment]
Can you post a log? (Found in /Users/<yourusername>/.config/Radarr/logs/sonarr.txt)

**Comment by petercockroach** [comment]
I had a quick look and didn't see anything, but hopefully it'll be more useful for you!

[sonarr.debug.0.txt](https://github.com/galli-leo/Radarr/files/692582/sonarr.debug.0.txt)
[sonarr.debug.txt](https://github.com/galli-leo/Radarr/files/692583/sonarr.debug.txt)
[sonarr.txt](https://github.com/galli-leo/Radarr/files/692584/sonarr.txt)

**Comment by onedr0p** [comment]
Can you try setting up transmission or deluge and see if that works? We don't know for sure if it's all download clients.

**Comment by petercockroach** [comment]
I'm getting the same issue. The box just disappears without any warning.

**Comment by onedr0p** [comment]
I just tried the latest version on my macbook air and it works fine for me. I also see no errors in the logs you posted. I bet it's a front end thing. Please open the chrome javascript console (crtl + shift + i) and try to add a download client and post any errors you see there.

**Comment by petercockroach** [comment]
Good call! It failed in Safari but worked in Chrome. Here's a log from Safari's javascript console:

[Log] Video not found (script.js, line 38)
[Log] message: videoCheck (script.js, line 13)
[Log] found: false (script.js, line 14)
[Debug] SignalR: [reconnecting] (main.js, line 224)
[Debug] SignalR: [connected] (main.js, line 224)
[Log] sync received, re-fetching collection (vendor.js, line 25280)
[Log] Video not found (script.js, line 38)
[Log] message: videoCheck (script.js, line 13)
[Log] found: false (script.js, line 14)

**Comment by onedr0p** [comment]
I wonder does Sonarr work for you in Safari?

**Comment by petercockroach** [comment]
Good point. I just tried it and it failed in Sonarr. Thanks for all the suggestions! I'll close this out.
