### ISSUE TITLE
Cant Search Some Movies

### ISSUE THREAD

**Issue by AcidRain999** [galli-leo/Radarr#71]
i was trying to add movies 1984 and 1941 and it wouldnt bring up any results. but i know the movies exist

also when i already have a movie in the database and another copy comes up, it cant find it to add it.
like Ace Ventura i have one copy that is HD and another that is SD that has the extended dolphin pool scene and only one can be added to the database.

Edit:

also we need the ability to change movies that it detects, it detected the movie the big short as the martian, but it doesnt give me the option to search for a different one, just show more options that are no where near it

**Comment by fedoranimus** [comment]
There are a lot of points wrapped up in this issue; please visit the Discord server for additional support and/or create issues for each bug/feature request.

Closing this issue for overloading.
