### ISSUE TITLE
Consider displaying quality "Status" along side the "Profile" in the Table view.

### ISSUE THREAD

**Issue by chrisallen** [galli-leo/Radarr#82]
Essentially this would allow you to know the current quality of a movie that you have on disk next to the profile quality that you desire.

Something along the lines of this.
![image](https://cloud.githubusercontent.com/assets/203867/21782783/8d3e054c-d719-11e6-9030-c1c104685ee2.png)

**Comment by Fossil01** [comment]
I'd call the column "Existing Quality", status is too ambiguous.

**Comment by galli-leo** [comment]
I can add a tooltip to the [Downloaded] badge in the table. Would that work as well?

**Comment by galli-leo** [comment]
Fixed in latest commit.

**Comment by chrisallen** [comment]
Adding a `Existing Quality` Column would be preferred if you can.
