### ISSUE TITLE
Doesn't start on Arch Linux

### ISSUE THREAD

**Issue by fryfrog** [galli-leo/Radarr#9]
Files installed to /usr/lib/radarr/

No file named "NzbDrone.Mono" found in install directory or from extraction of zip in _output directory.

Log file: https://ptpb.pw/2wx2

**Comment by galli-leo** [comment]
Yeah I haven't included the Linux package in this release. I will add that in v0.1.

**Comment by galli-leo** [comment]
Should be fixed in the latest release. Just use the Radarr_Mono_Version.zip download.

**Comment by fryfrog** [comment]
Starts up fine, ui even loads through reverse proxy. Mission accomplished.

**Comment by galli-leo** [comment]
Great to hear!
